#!/usr/bin/env python3
"""
MCP Server: ncbi_gene_search
Generated by: CygnusX MCP Builder
Version: 1.0.0
Description: 通过 NCBI E-utilities 搜索基因信息（需 egress 白名单包含 eutils.ncbi.nlm.nih.gov）
"""

__exp_mcp_generated__ = True

from mcp.server import Server
from mcp.types import Tool, TextContent
import json
import httpx

# ============ 配置 ============
DEFAULT_TIMEOUT = 30
# 显式声明允许访问的域名（需管理员加入 egress 白名单）
ALLOWED_DOMAINS = ["eutils.ncbi.nlm.nih.gov"]
BASE_URL = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"

# ============ 工具定义 ============
TOOLS = [
    Tool(
        name="search_gene",
        description="在 NCBI Gene 数据库中搜索基因信息，返回基因 ID、描述和物种",
        inputSchema={
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "搜索关键词（如基因名 BRCA1）"
                },
                "organism": {
                    "type": "string",
                    "description": "物种名（如 human, mouse），可选",
                    "default": "human"
                },
                "max_results": {
                    "type": "integer",
                    "description": "最大返回数",
                    "default": 5,
                    "minimum": 1,
                    "maximum": 20
                }
            },
            "required": ["query"],
        },
    )
]

# ============ 业务逻辑 ============
async def handle_search_gene(args: dict) -> list:
    """工具实现：NCBI 基因搜索"""
    try:
        query = args["query"]
        organism = args.get("organism", "human")
        max_results = args.get("max_results", 5)

        async with httpx.AsyncClient(timeout=DEFAULT_TIMEOUT) as client:
            # Step 1: 搜索基因 ID
            search_url = f"{BASE_URL}/esearch.fcgi"
            search_params = {
                "db": "gene",
                "term": f"{query}[Gene Name] AND {organism}[Organism]",
                "retmax": max_results,
                "retmode": "json"
            }
            resp = await client.get(search_url, params=search_params)
            resp.raise_for_status()
            search_result = resp.json()

            id_list = search_result.get("esearchresult", {}).get("idlist", [])
            if not id_list:
                return [TextContent(type="text", text=json.dumps(
                    {"query": query, "organism": organism, "results": [], "message": "未找到匹配基因"},
                    ensure_ascii=False
                ))]

            # Step 2: 获取基因详情
            summary_url = f"{BASE_URL}/esummary.fcgi"
            summary_params = {"db": "gene", "id": ",".join(id_list), "retmode": "json"}
            resp = await client.get(summary_url, params=summary_params)
            resp.raise_for_status()
            summary_result = resp.json()

            genes = []
            for gene_id in id_list:
                doc = summary_result.get("result", {}).get(gene_id, {})
                genes.append({
                    "gene_id": gene_id,
                    "name": doc.get("name", ""),
                    "description": doc.get("description", ""),
                    "organism": doc.get("organism", {}).get("scientificname", ""),
                })

            return [TextContent(type="text", text=json.dumps(
                {"query": query, "organism": organism, "count": len(genes), "results": genes},
                ensure_ascii=False
            ))]
    except httpx.HTTPError as e:
        return [TextContent(type="text", text=json.dumps(
            {"error": f"HTTP 请求失败: {str(e)}", "hint": "请检查 egress 白名单是否包含 eutils.ncbi.nlm.nih.gov"},
            ensure_ascii=False
        ))]
    except Exception as e:
        return [TextContent(type="text", text=json.dumps({"error": str(e)}, ensure_ascii=False))]

# ============ MCP 协议处理 ============
server = Server("ncbi_gene_search")

@server.list_tools()
async def list_tools() -> list:
    return TOOLS

@server.call_tool()
async def call_tool(name: str, arguments: dict) -> list:
    if name == "search_gene":
        return await handle_search_gene(arguments)
    raise ValueError(f"Unknown tool: {name}")

# ============ 入口（STDIO 模式，由 sandbox-agent 管理）============
if __name__ == "__main__":
    import asyncio
    from mcp.server.stdio import stdio_server

    async def main():
        async with stdio_server(server) as (read, write):
            await server.run(read, write, server.create_initialization_options())

    asyncio.run(main())
