#!/usr/bin/env python3
"""
MCP Server: csv_statistics
Generated by: OmicHub MCP Builder
Version: 1.0.0
Description: 对 CSV 文件计算基础统计指标
"""

__exp_mcp_generated__ = True

from mcp.server import Server
from mcp.types import Tool, TextContent
import json
import pandas as pd
from pathlib import Path

# ============ 工具定义 ============
TOOLS = [
    Tool(
        name="compute_csv_stats",
        description="读取 CSV 文件并计算指定数值列的统计指标（均值、标准差、中位数、最值）",
        inputSchema={
            "type": "object",
            "properties": {
                "file_path": {
                    "type": "string",
                    "description": "CSV 文件路径（相对 /workspace，如 data/sample.csv）"
                },
                "columns": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "要统计的列名列表，留空则统计所有数值列"
                }
            },
            "required": ["file_path"],
        },
    )
]

# ============ 业务逻辑 ============
async def handle_compute_csv_stats(args: dict) -> list:
    """工具实现：CSV 统计"""
    try:
        file_path = Path("/workspace") / args["file_path"]
        if not file_path.exists():
            return [TextContent(type="text", text=json.dumps(
                {"error": f"文件不存在: {args['file_path']}"}, ensure_ascii=False
            ))]

        df = pd.read_csv(file_path)
        columns = args.get("columns") or df.select_dtypes(include=["number"]).columns.tolist()

        stats = {}
        for col in columns:
            if col not in df.columns:
                continue
            series = df[col].dropna()
            stats[col] = {
                "count": int(series.count()),
                "mean": float(series.mean()),
                "std": float(series.std()),
                "min": float(series.min()),
                "median": float(series.median()),
                "max": float(series.max()),
            }

        return [TextContent(type="text", text=json.dumps(
            {"file": args["file_path"], "statistics": stats}, ensure_ascii=False
        ))]
    except Exception as e:
        return [TextContent(type="text", text=json.dumps({"error": str(e)}, ensure_ascii=False))]

# ============ MCP 协议处理 ============
server = Server("csv_statistics")

@server.list_tools()
async def list_tools() -> list:
    return TOOLS

@server.call_tool()
async def call_tool(name: str, arguments: dict) -> list:
    if name == "compute_csv_stats":
        return await handle_compute_csv_stats(arguments)
    raise ValueError(f"Unknown tool: {name}")

# ============ 入口（STDIO 模式，由 sandbox-agent 管理）============
if __name__ == "__main__":
    import asyncio
    from mcp.server.stdio import stdio_server

    async def main():
        async with stdio_server(server) as (read, write):
            await server.run(read, write, server.create_initialization_options())

    asyncio.run(main())
