data_delivery:
  delivery_mode: copy
  exclude_patterns: []
  include_patterns:
  - mapping_summary_table.csv
  - mapping_summary_paths.json
  - 02.mapping/STAR/sort_index/*.sort.bam
  - 02.mapping/STAR/sort_index/*.sort.bam.bai
  - 02.mapping/qualimap_report/*/
  - 02.mapping/samtools_flagstat/*_bam_flagstat.tsv
  - 02.mapping/samtools_stats/*_bam_stats.tsv
  - 02.mapping_report/multiqc_mapping_report.html
  # - 02.mapping/bamCoverage/*.bw
  include_qc_summary: true
  output_dir: ./mapping_delivery
  threads: 4