data_delivery:
  delivery_mode: copy
  exclude_patterns: []
  include_patterns:
  - variant_summary_table.csv
  - variant_summary_paths.json
  - 04.variant/gatk/*/*.final.pass.vcf
  - 04.variant/gatk/*/*.final.pass.vcf.idx
  - 04.variant/gatk/*/*.raw_variants.vcf
  - 04.variant/gatk/*/*.raw_variants.vcf.idx
  - 04.variant/gatk_bcftools_stats_pass/*/
  - 04.variant/gatk_bcftools_stats_raw/*/
  - 04.variant/multiqc_gatk_bcftools_stats_pass/
  - 04.variant/multiqc_gatk_bcftools_stats_raw/
  include_qc_summary: true
  output_dir: ./variant_delivery
  threads: 4