rule mark_duplicates:
    """
    Mark PCR duplicates using GATK MarkDuplicates and configure aligner-specific duplicate handling.

    This rule identifies and marks PCR duplicates in the BAM file, which are reads that
    originate from the same DNA fragment due to PCR amplification during library preparation.
    Duplicate marking is essential for accurate downstream analyses as PCR duplicates can
    skew coverage estimates, affect variant calling, and introduce bias in peak detection
    for ATAC-seq experiments.

    For aligner-specific duplicate handling:
    - When using Chromap as the aligner, this rule skips GATK MarkDuplicates because
      Chromap performs duplicate marking internally during the alignment process.
      The rule creates symbolic links to the input BAM file and generates a metrics
      file indicating that deduplication was handled by Chromap.
    - When using Bowtie2 or other aligners, this rule runs GATK MarkDuplicates
      to identify and mark duplicate reads based on alignment coordinates and
      read sequences.

    Key MarkDuplicates parameters:
    - CREATE_INDEX: Generates index for the output BAM file for rapid access
    - MAX_RECORDS_IN_RAM: Sets memory buffer size for sorting (5 million records)
    - SORTING_COLLECTION_SIZE_RATIO: Controls temporary file usage during sorting

    The duplicate marking process examines read pairs to identify those with
    identical alignment coordinates, which likely represent PCR duplicates of
    the same original DNA fragment. One read from each duplicate set is
    retained as the primary alignment, while others are marked with the
    DUPLICATE flag for downstream filtering.

    The metrics file generated by MarkDuplicates provides statistics about
    duplication rates, library complexity, and optical duplicates, which
    are valuable quality control metrics for assessing library preparation
    success and determining whether additional sequencing would be beneficial.
    """
    input:
        bam = '02.mapping/gatk/{sample}/{sample}.rg.bam',
        bai = '02.mapping/gatk/{sample}/{sample}.rg.bam.bai',
    output:
        bam = '02.mapping/gatk/{sample}/{sample}.rg.dedup.bam',
        bai = '02.mapping/gatk/{sample}/{sample}.rg.dedup.bai',
        metrics = '02.mapping/gatk/{sample}/{sample}.rg.dedup.metrics.txt',
    resources:
        **rule_resource(config, 'high_resource', skip_queue_on_local=True, logger=logger),
    conda:
        workflow.source_path("../../../envs/gatk.yaml")
    log:
        "logs/02.mapping/gatk/mark_dup_{sample}.log"
    benchmark:
        "benchmarks/02.mapping/gatk/mark_dup_{sample}.txt"
    threads: 2
    params:
        java_opts = get_java_opts,
    shell:
        """
        gatk --java-options "{params.java_opts}" MarkDuplicates \
                -I {input.bam} \
                -O {output.bam} \
                -M {output.metrics} \
                --CREATE_INDEX true \
                --MAX_RECORDS_IN_RAM 5000000 \
                --SORTING_COLLECTION_SIZE_RATIO 0.5 2>> {log}
        """
