"""initial_schema

Revision ID: 08ab25316cc1
Revises: 
Create Date: 2026-06-25 21:54:02.773494
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ab25316cc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('work_dir', sa.String(length=500), nullable=False),
    sa.Column('result_path', sa.String(length=500), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_flow_id'), 'tasks', ['flow_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('storage_quota', sa.Integer(), nullable=False),
    sa.Column('used_storage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cookie_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frozen_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_adjusted', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('frozen_reason', sa.Text(), nullable=True),
    sa.Column('frozen_by', sa.UUID(), nullable=True),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'frozen', 'suspended')", name='chk_account_status'),
    sa.ForeignKeyConstraint(['frozen_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_accounts_status', 'cookie_accounts', ['status'], unique=False, postgresql_where=sa.text("status != 'active'"))
    op.create_index('idx_accounts_updated_at', 'cookie_accounts', ['updated_at'], unique=False)
    op.create_table('cookie_pricing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pricing_type', sa.String(length=30), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('flow_category', sa.String(length=50), nullable=True),
    sa.Column('base_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("pricing_type IN ('task_type', 'resource', 'sandbox', 'bonus')", name='chk_pricing_type'),
    sa.CheckConstraint("unit IN ('per_task', 'per_hour', 'per_core_hour', 'per_gb_hour', 'per_session', 'per_user')", name='chk_pricing_unit'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pricing_effective', 'cookie_pricing', ['effective_from', 'effective_until'], unique=False)
    op.create_index('idx_pricing_query', 'cookie_pricing', ['flow_category', 'resource_type', 'priority'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_table('cookie_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_adjusted', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cookie_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_date', 'cookie_ledger', ['snapshot_date'], unique=False)
    op.create_index('idx_ledger_user_date', 'cookie_ledger', ['user_id', 'snapshot_date'], unique=False)
    op.create_table('cookie_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('txn_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('adjust_reason', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('resource_cores', sa.Integer(), nullable=True),
    sa.Column('resource_memory_gb', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('execution_seconds', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(txn_type NOT IN ('earn', 'adjust') OR amount >= 0) AND (txn_type NOT IN ('spend', 'freeze') OR amount <= 0)", name='chk_txn_amount_sign'),
    sa.ForeignKeyConstraint(['account_id'], ['cookie_accounts.id'], ),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_txn_account', 'cookie_transactions', ['account_id', 'created_at'], unique=False)
    op.create_index('idx_txn_source', 'cookie_transactions', ['source_type', 'source_id'], unique=False, postgresql_where=sa.text('source_id IS NOT NULL'))
    op.create_index('idx_txn_type_created', 'cookie_transactions', ['txn_type', 'created_at'], unique=False)
    op.create_index('idx_txn_user_created', 'cookie_transactions', ['user_id', 'created_at', 'txn_type'], unique=False, postgresql_using='btree')
    op.create_table('cookie_consumption_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('sandbox_session_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('billing_item', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("billing_item IN ('task_base', 'cpu_usage', 'memory_usage', 'execution_time', 'sandbox_session', 'sandbox_cpu', 'sandbox_memory')", name='chk_billing_item'),
    sa.ForeignKeyConstraint(['transaction_id'], ['cookie_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_logs_sandbox', 'cookie_consumption_logs', ['sandbox_session_id'], unique=False, postgresql_where=sa.text('sandbox_session_id IS NOT NULL'))
    op.create_index('idx_logs_task', 'cookie_consumption_logs', ['task_id'], unique=False, postgresql_where=sa.text('task_id IS NOT NULL'))
    op.create_index('idx_logs_transaction', 'cookie_consumption_logs', ['transaction_id'], unique=False)
    op.create_index('idx_logs_user_created', 'cookie_consumption_logs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_logs_user_created', table_name='cookie_consumption_logs')
    op.drop_index('idx_logs_transaction', table_name='cookie_consumption_logs')
    op.drop_index('idx_logs_task', table_name='cookie_consumption_logs', postgresql_where=sa.text('task_id IS NOT NULL'))
    op.drop_index('idx_logs_sandbox', table_name='cookie_consumption_logs', postgresql_where=sa.text('sandbox_session_id IS NOT NULL'))
    op.drop_table('cookie_consumption_logs')
    op.drop_index('idx_txn_user_created', table_name='cookie_transactions', postgresql_using='btree')
    op.drop_index('idx_txn_type_created', table_name='cookie_transactions')
    op.drop_index('idx_txn_source', table_name='cookie_transactions', postgresql_where=sa.text('source_id IS NOT NULL'))
    op.drop_index('idx_txn_account', table_name='cookie_transactions')
    op.drop_table('cookie_transactions')
    op.drop_index('idx_ledger_user_date', table_name='cookie_ledger')
    op.drop_index('idx_ledger_date', table_name='cookie_ledger')
    op.drop_table('cookie_ledger')
    op.drop_index('idx_pricing_query', table_name='cookie_pricing', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_index('idx_pricing_effective', table_name='cookie_pricing')
    op.drop_table('cookie_pricing')
    op.drop_index('idx_accounts_updated_at', table_name='cookie_accounts')
    op.drop_index('idx_accounts_status', table_name='cookie_accounts', postgresql_where=sa.text("status != 'active'"))
    op.drop_table('cookie_accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_flow_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
