"""add_blast_tables

Revision ID: 9c57efc91c12
Revises: 389356eeff9e
Create Date: 2026-07-14 14:50:30.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c57efc91c12"
down_revision: str | None = "389356eeff9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blast_databases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("db_key", sa.String(length=64), nullable=False),
        sa.Column("db_type", sa.String(length=16), nullable=False),
        sa.Column("source_species", sa.String(length=128), nullable=True),
        sa.Column("source_version", sa.String(length=64), nullable=True),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("file_size_mb", sa.Float(), nullable=False),
        sa.Column("sequence_count", sa.Integer(), nullable=False),
        sa.Column("build_status", sa.String(length=32), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("build_log", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("db_key"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_blast_databases_db_key"), "blast_databases", ["db_key"], unique=False)
    op.create_index(
        op.f("ix_blast_databases_db_type"), "blast_databases", ["db_type"], unique=False
    )
    op.create_index(
        op.f("ix_blast_databases_build_status"), "blast_databases", ["build_status"], unique=False
    )

    op.create_table(
        "blast_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("db_id", sa.UUID(), nullable=False),
        sa.Column("program", sa.String(length=16), nullable=False),
        sa.Column("query_title", sa.String(length=256), nullable=True),
        sa.Column("query_sequence", sa.Text(), nullable=False),
        sa.Column("query_file_path", sa.String(length=512), nullable=True),
        sa.Column("evalue", sa.Float(), nullable=False),
        sa.Column("max_target_seqs", sa.Integer(), nullable=False),
        sa.Column("word_size", sa.Integer(), nullable=True),
        sa.Column("gapopen", sa.Integer(), nullable=True),
        sa.Column("gapextend", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("result_format", sa.String(length=16), nullable=False),
        sa.Column("result_path", sa.String(length=512), nullable=True),
        sa.Column("result_size_kb", sa.Integer(), nullable=True),
        sa.Column("hit_count", sa.Integer(), nullable=True),
        sa.Column("top_hit_identity", sa.Float(), nullable=True),
        sa.Column("top_hit_evalue", sa.Float(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["db_id"], ["blast_databases.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.create_index(op.f("ix_blast_tasks_task_id"), "blast_tasks", ["task_id"], unique=False)
    op.create_index(op.f("ix_blast_tasks_user_id"), "blast_tasks", ["user_id"], unique=False)
    op.create_index(op.f("ix_blast_tasks_status"), "blast_tasks", ["status"], unique=False)
    op.create_index(
        op.f("ix_blast_tasks_submitted_at"), "blast_tasks", ["submitted_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blast_tasks_submitted_at"), table_name="blast_tasks")
    op.drop_index(op.f("ix_blast_tasks_status"), table_name="blast_tasks")
    op.drop_index(op.f("ix_blast_tasks_user_id"), table_name="blast_tasks")
    op.drop_index(op.f("ix_blast_tasks_task_id"), table_name="blast_tasks")
    op.drop_table("blast_tasks")
    op.drop_index(op.f("ix_blast_databases_build_status"), table_name="blast_databases")
    op.drop_index(op.f("ix_blast_databases_db_type"), table_name="blast_databases")
    op.drop_index(op.f("ix_blast_databases_db_key"), table_name="blast_databases")
    op.drop_table("blast_databases")
    # ### end Alembic commands ###
