"""add_notification_table

Revision ID: c72c373d1ee2
Revises: 25287a65dfe7
Create Date: 2026-06-26 16:36:57.830000
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c72c373d1ee2'
down_revision: str | None = '25287a65dfe7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('read_by', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_by'), 'notifications', ['created_by'], unique=False)
    op.create_index(op.f('ix_notifications_target_user_id'), 'notifications', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_target_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_by'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
