#!/usr/bin/env python3
"""Render Worker path settings from YAML into a shell-compatible env file."""

from __future__ import annotations

import argparse
import shlex
import sys
from pathlib import Path
from typing import Any

import yaml


REQUIRED_PATHS = {
    "shared_data_dir": "WORKER_SHARED_DATA_DIR",
    "pipeline_dir": "WORKER_PIPELINE_DIR",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render data/worker_config.yaml for Docker Compose interpolation."
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("data/worker_config.yaml"),
        help="Worker YAML configuration path.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data/.worker-config.env"),
        help="Generated shell environment file path.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate the YAML without writing the output file.",
    )
    return parser.parse_args()


def load_paths(config_path: Path) -> dict[str, str]:
    try:
        raw_config: Any = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise ValueError(f"Worker configuration does not exist: {config_path}") from error
    except yaml.YAMLError as error:
        raise ValueError(f"Invalid YAML in {config_path}: {error}") from error

    if not isinstance(raw_config, dict) or not isinstance(raw_config.get("paths"), dict):
        raise ValueError(f"{config_path} must define a 'paths' mapping.")

    paths = raw_config["paths"]
    rendered: dict[str, str] = {}
    for yaml_key, environment_key in REQUIRED_PATHS.items():
        value = paths.get(yaml_key)
        if not isinstance(value, str) or not value.strip():
            raise ValueError(f"paths.{yaml_key} must be a non-empty absolute path.")
        path = Path(value).expanduser()
        if not path.is_absolute():
            raise ValueError(f"paths.{yaml_key} must be absolute: {value}")
        rendered[environment_key] = str(path)

    return rendered


def render_environment(values: dict[str, str], config_path: Path) -> str:
    lines = [
        "# Generated by scripts/render_worker_config.py; do not edit.",
        f"# Source: {config_path}",
    ]
    lines.extend(f"{key}={shlex.quote(value)}" for key, value in values.items())
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    try:
        values = load_paths(args.config)
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    if args.check:
        print(f"Worker configuration is valid: {args.config}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_environment(values, args.config), encoding="utf-8")
    print(f"Rendered Worker configuration: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
